compressionLevel: 9

enableGlobalCache: true

enableImmutableInstalls: false

enableMirror: true

enableScripts: false

enableTelemetry: false

initFields:
  private: true
  type: module

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@headlessui/react@*":
    peerDependencies:
      react: "*"
      react-dom: "*"

preferInteractive: true
