nodeLinker: node-modules
enableScripts: true
enableGlobalCache: true

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@headlessui/react@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
